config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users, controllers:
    {registrations: "users/registrations",
      confirmations: "users/confirmations",
      sessions: "users/sessions",
      passwords: "users/passwords",
      unlocks: "users/unlocks",
      omniauth_callbacks: "users/omniauth_callbacks"}

  resources :users, only: %i(new create show) do
    resources :bookings do
      member do
        patch :cancel
      end
    end
  end
  resources :account_activations, only: :edit

  namespace :admin do
    get "/", to: "admin#index"
    resources :tours do
      member do
        #remove_image_admin_tour_path
        delete :remove_image
      end
    end
    resources :vouchers
    resources :bookings, only: %i(index show destroy update)
  end

  resources :tours, only: %i(index show) do
    resources :bookings
    resources :reviews
  end
  root "static_pages#home"

  namespace :api do
    namespace :v1 do
      resources :tours
      resources :users
      post "users/sign_in", to: "users#sign_in"
      resources :reviews
    end
  end
end

app/models/tour.rb
class Tour < ApplicationRecord
  TOUR_ATTRIBUTES = %i(
    tour_name
    city
    tour_destination
    description
    price
    day_duration
    min_guests
    max_guests
    deposit_percent
    status
    tour_type_id
    images: []
  ).freeze

  SEARCH_ATTRIBUTES = %i(
    name
    start_date
    min_duration
    max_duration
    min_price
    max_price
    city
    tour_type_id
    status
  ).freeze

  enum status: {preparing: 0, active: 1, removed: 2}
  belongs_to :tour_type
  has_many :tour_flights, dependent: :destroy
  has_many :flights, through: :tour_flights
  has_many :bookings, dependent: :destroy
  has_many :reviews, dependent: :destroy

  validates :tour_name, presence: true,
                        length: {maximum: Settings.tour.max_len_name}
  validates :city, :tour_destination, :description, presence: true
  validates :day_duration, presence: true,
                           numericality: {only_integer: true,
                                          maximum: Settings.tour.max_duration,
                                          greater_than: Settings.digit_0}
  validates :price, presence: true,
                    numericality: {greater_than: Settings.digit_0}

  validates :min_guests, presence: true,
                         numericality: {only_integer: true,
                                        greater_than: Settings.digit_0}
  validates :max_guests, presence: true,
                         numericality: {only_integer: true,
                                        greater_than: Settings.digit_0}
  validates :deposit_percent, presence: true,
                              numericality: {greater_than: Settings.digit_0,
                                             less_than: Settings.digit_100}

  # Ensure max_guests is greater than or equal to min_guests
  validate :max_guests_greater_than_or_equal_to_min_guests

  has_many_attached :images do |attachable|
    attachable.variant :display, resize_to_limit: Settings.tour.limit_250_250
  end
  scope :upcoming, ->{order start_date: :asc}

  scope :order_by_status, ->{order status: :asc}

  scope :by_name, lambda {|name|
    where("tour_name LIKE ?", "%#{sanitize_sql_like(name)}%") if name.present?
  }

  scope :by_city, lambda {|city|
    where("city LIKE ?", "%#{sanitize_sql_like(city)}%") if city.present?
  }

  scope :by_status, (lambda do |statuses|
    return if statuses.blank?

    ransack(status_in: statuses).result
  end)
  scope :by_destination, lambda {|tour_destination|
    if tour_destination.present?
      sanitized_destination = sanitize_sql_like(tour_destination)
      where("tour_destination LIKE ?", "%#{sanitized_destination}%")
    end
  }
  scope :by_start_date, lambda {|start_date|
    where("start_date >= ?", start_date.presence ||
    Settings.tour.search.start_date)
  }
  scope :by_tour_type_id, lambda {|tour_type_id|
    return if tour_type_id.to_i == 1 || tour_type_id.blank?

    where("tour_type_id = ?", tour_type_id)
  }

  def self.ransackable_attributes _auth_object = nil
    %w(
      tour_name
      day_duration
      city price
      status
      tour_destination
      address
      deposit_percent
    )
  end

  def self.ransackable_scopes _auth_object = nil
    %w(by_status by_started_date)
  end

  def self.ransackable_associations _auth_object = nil
    %w(bookings)
  end

  ransack_alias :address, :city_or_tour_destination

  private

  def max_guests_greater_than_or_equal_to_min_guests
    if max_guests.present? && min_guests.present? && max_guests < min_guests
      errors.add(:max_guests, I18n.t("errors.min_guest_greater_max_guest"))
    end
  end

  def start_date_after_today
    return if start_date.blank?

    return unless start_date <= Time.zone.today

    errors.add(:start_date, I18n.t("errors.start_date_today"))
  end
end

app/models/tour_type.rb
class TourType < ApplicationRecord
  has_many :tours, dependent: :destroy
  has_ancestry
end

app/controllers/admin/tours_controller.rb
class Admin::ToursController < Admin::AdminController
  include Admin::ToursHelper
  before_action :set_breadcrumbs
  before_action :set_tour, only: %i(show edit update remove_image)
  before_action :set_uploaded_images, only: %i(create update resize_before_save)
  before_action :resize_before_save, only: %i(create update)
  load_and_authorize_resource

  def index
    @q = Tour.ransack(params[:q])
    @tours = @q.result.by_status(params[:statuses]).order_by_status
    @pagy, @tours = pagy(@tours, items: Settings.digit_10)
  end

  def show
    add_breadcrumb(@tour.tour_name, admin_tours_path(@tour))
  end

  def new
    @tour = Tour.new
  end

  def create
    @tour = Tour.new(tour_params)
    if @tour.save && check_image_limits(@tour, @uploaded_images)
      @tour.images.attach(@uploaded_images) if @uploaded_images.present?
      flash[:success] = t "flash.tour.create_success"
      redirect_to admin_tours_path, status: :see_other
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    add_breadcrumb(@tour.tour_name, admin_tours_path(@tour))
    add_breadcrumb(t("edit"))
  end

  def update
    if can_edit_tour(@tour)
      if @tour.update(tour_params) &&
         check_image_limits(@tour, @uploaded_images)

        @tour.images.attach(@uploaded_images) if @uploaded_images.present?
        flash[:success] = t "flash.tour.update_success"
        redirect_to admin_tours_path, status: :see_other
      else
        render :edit, status: :unprocessable_entity
      end
    else
      flash.now[:danger] = t "flash.tour.invalid_update"
      render :edit, status: :unprocessable_entity
    end
  end

  def remove_image
    image = @tour.images.find(params[:image_id])
    image.purge
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.remove("image_#{params[:image_id]}")
      end
    end
  end

  private

  def set_breadcrumbs
    add_breadcrumb(t("breadcrumb.home"), admin_path)
    add_breadcrumb(t("breadcrumb.tours"), admin_tours_path)
  end

  def check_image_limits record, images
    if total_image_count_exceeds_limit?(record.images.count, images,
                                        Settings.images_limit)
      @tour.errors.add(:images, I18n.t("errors.images_limit",
                                       limit: Settings.images_limit))
      return false
    end
    true
  end

  def set_tour
    @tour = Tour.find(params[:id])
    return if @tour

    redirect_to admin_tours_path, status: :see_other
    flash[:danger] = t "flash.tour.not_exist"
  end

  def set_uploaded_images
    @uploaded_images = filter_uploaded_images(params.dig(:tour, :images))
  end

  def tour_params
    params.require(:tour).permit Tour::TOUR_ATTRIBUTES
  end

  def resize_before_save
    return unless @uploaded_images

    @uploaded_images.each do |image|
      resize_result = resize_image(image,
                                   Settings.width_img_250,
                                   Settings.height_img_250)
      break unless resize_result
    end
  end

  def resize_image image_param, width, height
    return false unless image_param

    begin
      image = MiniMagick::Image.read(image_param)
      image.resize "#{width}x#{height}"
      image.write(image_param.tempfile.path)
      true
    rescue StandardError => _e
      flash.now[:danger] = I18n.t("flash.tour.invalid_image",
                                  image_name: image_param.original_filename)
      render :edit, status: :unprocessable_entity
      false
    end
  end

  def search_tours params
    Tour.by_name(params[:keyword])
        .or(Tour.by_city(params[:keyword]))
        .or(Tour.by_destination(params[:keyword]))
        .by_status(params[:status])
  end
end

app/controllers/api/v1/tours_controller.rb
class Api::V1::ToursController < Api::V1::ApplicationController
  before_action :authorized, except: %i(index show)
  before_action :set_tour, only: %i(show update destroy)

  # GET /api/v1/tours
  def index
    @tours = Tour.by_name(params[:name])
                 .by_status(params[:statuses])
                 .by_city(params[:city])

    render json: @tours, each_serializer: TourSerializer, status: :ok
  end

  # GET /api/v1/tours/:id
  def show
    render json: @tour, serializer: TourSerializer, status: :ok
  end

  # POST /api/v1/tours
  def create
    @tour = Tour.new(tour_params)

    if @tour.save
      render json: @tour, serializer: TourSerializer, status: :created
    else
      render json: ErrorSerializer.serialize(@tour.errors),
             status: :unprocessable_entity
    end
  end

  # PUT /api/v1/tours/:id
  def update
    if @tour.update(tour_params)
      render json: @tour, serializer: TourSerializer, status: :ok
    else
      render json: ErrorSerializer.serialize(@tour.errors),
             status: :unprocessable_entity
    end
  end

  # DELETE /api/v1/tours/:id
  def destroy
    if @tour.destroy
      render json: {
        status: true,
        message: I18n.t("api.tours.delete")
      }, status: :ok
    else
      render json: ErrorSerializer.serialize(@tour.errors),
             status: :unprocessable_entity
    end
  end

  private

  def set_tour
    @tour = Tour.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    render json: {
      status: false,
      message: I18n.t("api.tours.not_found")
    }, status: :not_found
  end

  def tour_params
    params.require(:tour).permit Tour::TOUR_ATTRIBUTES
  end
end

app/controllers/tours_controller.rb
class ToursController < ApplicationController
  before_action :tour, only: :show
  load_and_authorize_resource

  def show
    @relevant_pagy,
    @relevant_tours = pagy(Tour.by_tour_type_id(@tour.tour_type_id),
                           items: Settings.tour.rev_tours_per_page)

    @reviews = @tour.reviews.order_by_create_at
    return if params[:star].blank?

    @reviews = @reviews.by_rating(params[:star])
  end

  def index
    @q = Tour.ransack(params[:q])
    @tours = @q.result.by_status(params[:statuses])
    @pagy, @tours = pagy(@tours, items: Settings.tour.items_per_page)
  end

  private

  def tour
    @tour = Tour.find_by(id: params[:id])
    return if @tour.present?

    flash[:danger] = t "flash.tour.find_tour_failed"
    redirect_to tours_path
  end

  def search
    Tour::SEARCH_ATTRIBUTES.each do |field|
      @tours = @tours.public_send "by_#{field}", params[field]
    end
  end
end

app/helpers/admin/tours_helper.rb
module Admin::ToursHelper
  def filter_uploaded_images images
    images.select{|item| item.is_a?(ActionDispatch::Http::UploadedFile)}
  end

  def total_image_count_exceeds_limit? current_count, new_images, limit
    current_count + new_images.count > limit
  end

  def can_edit_tour tour
    tour.bookings.pending_or_past_confirmed.blank?
  end
end

app/views/admin/tours/_form.html.erb
<%= form_with(model: [:admin, @tour]) do |f| %>
  <div class="row">
    <div class="col-md-6">
      <div class="form-group mb-4">
        <%= f.label :tour_name, class: "fw-bold mb-2" %>
        <small class="text-danger fw-bold">*</small>
        <%= f.text_field :tour_name, class: "form-control" %>
      </div>

      <div class="form-group mb-4">
        <%= f.label :city, class: "fw-bold mb-2" %>
        <small class="text-danger fw-bold">*</small>
        <%= f.text_field :city, class: "form-control" %>
      </div>

      <div class="form-group mb-4">
        <%= f.label :tour_destination, class: "fw-bold mb-2" %>
        <small class="text-danger fw-bold">*</small>
        <%= f.text_field :tour_destination, class: "form-control" %>
      </div>

      <div class="form-group mb-4">
        <%= f.label :description, class: "fw-bold mb-2" %>
        <small class="text-danger fw-bold">*</small>
        <%= f.text_area :description, class: "form-control" %>
      </div>

      <div class="container my-3">
        <% if @tour.images.attached? %>
          <% @tour.images.each do |image| %>
            <%= f.hidden_field :images, multiple: true, value: image.signed_id %>
          <% end %>
        <% end %>

        <div class="container my-4">
          <%= render "show_images", tour: @tour %>
        </div>
        <div class="mt-3">
          <%= f.file_field :images, accept: Settings.img_format,
                                    multiple: true, class: "form-control" %>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="form-group mb-4">
        <%= f.label :price, class: "fw-bold mb-2" %>
        <small class="text-danger fw-bold">*</small>
        <%= f.number_field :price, class: "form-control", min: 1 %>
      </div>

      <div class="form-group mb-4">
        <%= f.label :day_duration, class: "fw-bold mb-2" %>
        <small class="text-danger fw-bold">*</small>
        <%= f.number_field :day_duration, class: "form-control", min: 1 %>
      </div>

      <div class="form-group mb-4">
        <%= f.label :min_guests, class: "fw-bold mb-2" %>
        <small class="text-danger fw-bold">*</small>
        <%= f.number_field :min_guests, class: "form-control", min: 1 %>
      </div>

      <div class="form-group mb-4">
        <%= f.label :max_guests, class: "fw-bold mb-2" %>
        <small class="text-danger fw-bold">*</small>
        <%= f.number_field :max_guests, class: "form-control", min: 1 %>
      </div>

      <div class="form-group mb-4">
        <%= f.label :deposit_percent, class: "fw-bold mb-2" %>
        <small class="text-danger fw-bold">*</small>
        <%= f.number_field :deposit_percent, class: "form-control", min: 0, max: 100,step: 0.01 %>
      </div>

      <div class="form-group mb-4">
        <%= f.label :status, class: "fw-bold mb-2" %>
        <small class="text-danger fw-bold">*</small>
        <%= f.collection_select :status, Tour.statuses.keys, :to_s, :humanize, {}, { class: "form-control" } %>
      </div>

      <div class="form-group mb-4">
        <%= f.label :tour_type_id, class: "fw-bold mb-2" %>
        <small class="text-danger fw-bold">*</small>
        <%= f.collection_select :tour_type_id, TourType.all, :id, :type_name, {},
                                              { class: "form-control" } %>
      </div>
      <div class="actions py-4">
        <%= f.submit class: "btn btn-primary w-100" %>
      </div>
    </div>
  </div>
<% end %>

app/views/admin/tours/_image-action.html.erb
<div class="position-relative m-2" id="image_<%= image.id %>">
  <%= image_tag(image, size: Settings.img_tag_size, class: "img-thumbnail") %>
  <%= link_to "x", remove_image_admin_tour_path(id: @tour.id, image_id: image.id),
                   data: { turbo_method: :delete },
                   class: "position-absolute top-0 end-0 text-danger fw-bold px-1" %>
</div>

app/views/admin/tours/_image.html.erb
<div class="position-relative m-2">
  <%= image_tag(image, size: Settings.img_tag_size, class: "img-thumbnail") %>
</div>

app/views/admin/tours/_search_form.html.erb
<%= search_form_for @q, url: admin_tours_path, class: "form-inline g-5" do |f| %>
  <div class="row mb-4">
    <div class="col-md-6">
      <%= f.search_field :city_or_tour_destination_or_price_or_day_duration_cont,
            class: "form-control border-2", placeholder: t("search_by_keyword") %>
    </div>
    <div class="col-md-6 py-2">
      <% Tour.statuses.each do |key, value| %>
        <div class="form-check form-check-inline">
          <%= check_box_tag "statuses[]", value, params[:statuses].present? && params[:statuses].include?(value), class: "form-check-input" %>
          <%= label_tag "tours.status.#{value}", t("tours.statuses.#{key}"), class: "form-check-label" %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12">
      <div class="row d-flex justify-content-start flex-wrap">
        <div class="col-md-2">
          <%= f.label :price_gteq, t("price_from"), class: "form-label fw-bold" %>
          <%= f.number_field :price_gteq, class: "form-control" %>
        </div>
        <div class="col-md-2">
          <%= f.label :price_lteq, t("price_to"), class: "form-label fw-bold" %>
          <%= f.number_field :price_lteq, class: "form-control" %>
        </div>
        <div class="col-md-2">
          <%= f.label :deposit_percent_gteq, t("deposit_min"), class: "form-label fw-bold" %>
          <%= f.number_field :deposit_percent_gteq, class: "form-control" %>
        </div>
        <div class="col-md-2">
          <%= f.label :deposit_percent_lteq, t("deposit_max"), class: "form-label fw-bold" %>
          <%= f.number_field :deposit_percent_lteq, class: "form-control" %>
        </div>
        <div class="col-md-2">
          <%= f.label :day_duration_gteq, t("duration_from"), class: "form-label fw-bold" %>
          <%= f.number_field :day_duration_gteq, class: "form-control" %>
        </div>
        <div class="col-md-2">
          <%= f.label :day_duration_lteq, t("duration_to"), class: "form-label fw-bold" %>
          <%= f.number_field :day_duration_lteq, class: "form-control" %>
        </div>
      </div>
    </div>
    <div class="mt-3">
      <div class="d-flex flex-nowrap align-items-center">
        <%= submit_tag t("search"), class: "btn btn-outline-success px-3" %>
        <%= link_to t("refresh"), admin_tours_path, class: "btn btn-secondary mx-3 px-3" %>
      </div>
    </div>
  </div>

<% end %>

app/views/admin/tours/_show_images.html.erb
<% if @tour.images.attached? %>
  <div class="d-flex flex-wrap">
    <% @tour.images.each do |image| %>
      <%= render "image-action", image: image %>
    <% end %>
  </div>
<% end %>

app/views/admin/tours/edit.html.erb
<div class="container px-5">
  <h3 class="pb-2"><%= t "tour_detail" %></h3>
  <%= render "shared/error_messages", resource: @tour  %>
  <%= render "form" %>
</div>

app/views/admin/tours/index.html.erb
<section class="intro">
  <div class="gradient-custom-1 h-100">
    <div class="mask d-flex align-items-center h-100">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-12">
            <div class="shadow-sm py-3 mb-3 bg-white rounded px-3">
              <%= render "search_form" %>
            </div>
            <div class="table-responsive bg-white">
              <table class="table mb-0 table-striped">
                <thead>
                  <tr>
                    <th scope="col"><%= t "stt" %></th>
                    <th scope="col"><%= t "tour_name" %></th>
                    <th scope="col"><%= t "city" %></th>
                    <th scope="col"><%= t "tour_destination" %></th>
                    <th scope="col"><%= t "price" %></th>
                    <th scope="col"><%= t "day_duration" %></th>
                    <th scope="col"><%= t "deposit" %>(%)</th>
                    <th scope="px-5"><%= t "status" %></th>
                  </tr>
                </thead>
                <tbody>
                  <% @tours.each_with_index do |tour, index| %>
                    <tr>
                      <td><%= index+1 %></td>
                      <td scope="row" class="fst-italic"><%= tour.tour_name %></td>
                      <td><%= tour.city %></td>
                      <td><%= truncate(tour.tour_destination, length: Settings.digit_30, omission: "....") %></td>
                      <td><%= number_to_currency(tour.price) %></td>
                      <td class="text-center"><%= tour.day_duration %></td>
                      <td class="text-center"><%= tour.deposit_percent %>%</td>
                      <td class="text-center"><%= status_badge(tour.status) %></td>
                      <td><%= link_to t("view"), admin_tour_path(tour), class: "btn text-primary" %></td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="d-flex justify-content-between py-4">
      <%= link_to t("create_new"), new_admin_tour_path, class: "btn btn-primary" %>
      <%== pagy_nav(@pagy) %>
    </div>
  </div>
</section>

app/views/admin/tours/new.html.erb
<div class="container px-5">
  <h3 class="pb-2"><%= t "create_new" %></h3>
  <%= render "shared/error_messages", resource: @tour  %>
  <%= render "form" %>
</div>

app/views/admin/tours/show.html.erb
<div class="container px-5">
  <div class="container">
    <div class="card">
      <div class="card-header">
        <h5><%= t "tour_details" %></h5>
      </div>
      <div class="card-body px-5">
        <div class="d-flex flex-wrap justify-content-center">
          <div class="col-7">
            <div class="row mb-4">
              <div class="col-md-5 fw-bold"><%= t "tours.tour_name" %>:</div>
              <div class="col-md-7"><%= @tour.tour_name %></div>
            </div>
            <div class="row mb-4">
              <div class="col-md-5 fw-bold"><%= t "tours.tour_destination" %>:</div>
              <div class="col-md-7"><%= @tour.tour_destination %></div>
            </div>
            <div class="row mb-4">
              <div class="col-md-5 fw-bold"><%=t "tours.city" %>:</div>
              <div class="col-md-7"><%= @tour.city %></div>
            </div>
          </div>
          <div class="col-5">
            <div class="row mb-4">
              <div class="col-md-5 fw-bold"><%= t "min_guest" %>:</div>
              <div class="col-md-7"><%= @tour.min_guests %></div>
            </div>
            <div class="row mb-4">
              <div class="col-md-5 fw-bold"><%= t "max_guest" %>:</div>
              <div class="col-md-7"><%= @tour.max_guests %></div>
            </div>
            <div class="row mb-4">
              <div class="col-md-5 fw-bold"><%= t "tours.tour_type" %>:</div>
              <div class="col-md-7"><%= @tour.tour_type.type_name %></div>
            </div>
             <div class="row mb-4">
              <div class="col-md-5 fw-bold"><%= t "deposit_percent" %>:</div>
              <div class="col-md-7"><%= @tour.deposit_percent %>%</div>
            </div>
          </div>
          <div class="col-12">
            <div class="row mb-4">
              <p class="fw-bold"><%= t "tour.description" %>:</p>
              <div class="mx-2">
                <p><%= @tour.description %></p>
              </div>
            </div>
          </div>
          <div class="col-12">
          <h5><%= t "tours.images" %></h5>
          <% if @tour.images.attached? %>
            <div class="d-flex flex-wrap">
              <%= render partial: "image", collection: @tour.images %>
            </div>
          <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="d-flex justify-content-end py-4">
      <%= link_to t("back"), admin_tours_path, class: "btn btn-primary me-3 px-3" %>
      <% if can_edit_tour(@tour) %>
        <%= link_to t("edit"), edit_admin_tour_path(@tour), class: "btn btn-success me-3 px-4" %>
      <% end %>
    </div>
  </div>
</div>