config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users, controllers:
    {registrations: "users/registrations",
      confirmations: "users/confirmations",
      sessions: "users/sessions",
      passwords: "users/passwords",
      unlocks: "users/unlocks",
      omniauth_callbacks: "users/omniauth_callbacks"}

  resources :users, only: %i(new create show) do
    resources :bookings do
      member do
        patch :cancel
      end
    end
  end
  resources :account_activations, only: :edit

  namespace :admin do
    get "/", to: "admin#index"
    resources :tours do
      member do
        #remove_image_admin_tour_path
        delete :remove_image
      end
    end
    resources :vouchers
    resources :bookings, only: %i(index show destroy update)
  end

  resources :tours, only: %i(index show) do
    resources :bookings
    resources :reviews
  end
  root "static_pages#home"

  namespace :api do
    namespace :v1 do
      resources :tours
      resources :users
      post "users/sign_in", to: "users#sign_in"
      resources :reviews
    end
  end
end

app/models/tour.rb
class Tour < ApplicationRecord
  TOUR_ATTRIBUTES = %i(
    tour_name
    city
    tour_destination
    description
    price
    day_duration
    min_guests
    max_guests
    deposit_percent
    status
    tour_type_id
    images: []
  ).freeze

  SEARCH_ATTRIBUTES = %i(
    name
    start_date
    min_duration
    max_duration
    min_price
    max_price
    city
    tour_type_id
    status
  ).freeze

  enum status: {preparing: 0, active: 1, removed: 2}
  belongs_to :tour_type
  has_many :tour_flights, dependent: :destroy
  has_many :flights, through: :tour_flights
  has_many :bookings, dependent: :destroy
  has_many :reviews, dependent: :destroy

  validates :tour_name, presence: true,
                        length: {maximum: Settings.tour.max_len_name}
  validates :city, :tour_destination, :description, presence: true
  validates :day_duration, presence: true,
                           numericality: {only_integer: true,
                                          maximum: Settings.tour.max_duration,
                                          greater_than: Settings.digit_0}
  validates :price, presence: true,
                    numericality: {greater_than: Settings.digit_0}

  validates :min_guests, presence: true,
                         numericality: {only_integer: true,
                                        greater_than: Settings.digit_0}
  validates :max_guests, presence: true,
                         numericality: {only_integer: true,
                                        greater_than: Settings.digit_0}
  validates :deposit_percent, presence: true,
                              numericality: {greater_than: Settings.digit_0,
                                             less_than: Settings.digit_100}

  # Ensure max_guests is greater than or equal to min_guests
  validate :max_guests_greater_than_or_equal_to_min_guests

  has_many_attached :images do |attachable|
    attachable.variant :display, resize_to_limit: Settings.tour.limit_250_250
  end
  scope :upcoming, ->{order start_date: :asc}

  scope :order_by_status, ->{order status: :asc}

  scope :by_name, lambda {|name|
    where("tour_name LIKE ?", "%#{sanitize_sql_like(name)}%") if name.present?
  }

  scope :by_city, lambda {|city|
    where("city LIKE ?", "%#{sanitize_sql_like(city)}%") if city.present?
  }

  scope :by_status, (lambda do |statuses|
    return if statuses.blank?

    ransack(status_in: statuses).result
  end)
  scope :by_destination, lambda {|tour_destination|
    if tour_destination.present?
      sanitized_destination = sanitize_sql_like(tour_destination)
      where("tour_destination LIKE ?", "%#{sanitized_destination}%")
    end
  }
  scope :by_start_date, lambda {|start_date|
    where("start_date >= ?", start_date.presence ||
    Settings.tour.search.start_date)
  }
  scope :by_tour_type_id, lambda {|tour_type_id|
    return if tour_type_id.to_i == 1 || tour_type_id.blank?

    where("tour_type_id = ?", tour_type_id)
  }

  def self.ransackable_attributes _auth_object = nil
    %w(
      tour_name
      day_duration
      city price
      status
      tour_destination
      address
      deposit_percent
    )
  end

  def self.ransackable_scopes _auth_object = nil
    %w(by_status by_started_date)
  end

  def self.ransackable_associations _auth_object = nil
    %w(bookings)
  end

  ransack_alias :address, :city_or_tour_destination

  private

  def max_guests_greater_than_or_equal_to_min_guests
    if max_guests.present? && min_guests.present? && max_guests < min_guests
      errors.add(:max_guests, I18n.t("errors.min_guest_greater_max_guest"))
    end
  end

  def start_date_after_today
    return if start_date.blank?

    return unless start_date <= Time.zone.today

    errors.add(:start_date, I18n.t("errors.start_date_today"))
  end
end

app/models/tour_type.rb
class TourType < ApplicationRecord
  has_many :tours, dependent: :destroy
  has_ancestry
end

app/controllers/admin/tours_controller.rb
class Admin::ToursController < Admin::AdminController
  include Admin::ToursHelper
  before_action :set_breadcrumbs
  before_action :set_tour, only: %i(show edit update remove_image)
  before_action :set_uploaded_images, only: %i(create update resize_before_save)
  before_action :resize_before_save, only: %i(create update)
  load_and_authorize_resource

  def index
    @q = Tour.ransack(params[:q])
    @tours = @q.result.by_status(params[:statuses]).order_by_status
    @pagy, @tours = pagy(@tours, items: Settings.digit_10)
  end

  def show
    add_breadcrumb(@tour.tour_name, admin_tours_path(@tour))
  end

  def new
    @tour = Tour.new
  end

  def create
    @tour = Tour.new(tour_params)
    if @tour.save && check_image_limits(@tour, @uploaded_images)
      @tour.images.attach(@uploaded_images) if @uploaded_images.present?
      flash[:success] = t "flash.tour.create_success"
      redirect_to admin_tours_path, status: :see_other
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    add_breadcrumb(@tour.tour_name, admin_tours_path(@tour))
    add_breadcrumb(t("edit"))
  end

  def update
    if can_edit_tour(@tour)
      if @tour.update(tour_params) &&
         check_image_limits(@tour, @uploaded_images)

        @tour.images.attach(@uploaded_images) if @uploaded_images.present?
        flash[:success] = t "flash.tour.update_success"
        redirect_to admin_tours_path, status: :see_other
      else
        render :edit, status: :unprocessable_entity
      end
    else
      flash.now[:danger] = t "flash.tour.invalid_update"
      render :edit, status: :unprocessable_entity
    end
  end

  def remove_image
    image = @tour.images.find(params[:image_id])
    image.purge
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.remove("image_#{params[:image_id]}")
      end
    end
  end

  private

  def set_breadcrumbs
    add_breadcrumb(t("breadcrumb.home"), admin_path)
    add_breadcrumb(t("breadcrumb.tours"), admin_tours_path)
  end

  def check_image_limits record, images
    if total_image_count_exceeds_limit?(record.images.count, images,
                                        Settings.images_limit)
      @tour.errors.add(:images, I18n.t("errors.images_limit",
                                       limit: Settings.images_limit))
      return false
    end
    true
  end

  def set_tour
    @tour = Tour.find(params[:id])
    return if @tour

    redirect_to admin_tours_path, status: :see_other
    flash[:danger] = t "flash.tour.not_exist"
  end

  def set_uploaded_images
    @uploaded_images = filter_uploaded_images(params.dig(:tour, :images))
  end

  def tour_params
    params.require(:tour).permit Tour::TOUR_ATTRIBUTES
  end

  def resize_before_save
    return unless @uploaded_images

    @uploaded_images.each do |image|
      resize_result = resize_image(image,
                                   Settings.width_img_250,
                                   Settings.height_img_250)
      break unless resize_result
    end
  end

  def resize_image image_param, width, height
    return false unless image_param

    begin
      image = MiniMagick::Image.read(image_param)
      image.resize "#{width}x#{height}"
      image.write(image_param.tempfile.path)
      true
    rescue StandardError => _e
      flash.now[:danger] = I18n.t("flash.tour.invalid_image",
                                  image_name: image_param.original_filename)
      render :edit, status: :unprocessable_entity
      false
    end
  end

  def search_tours params
    Tour.by_name(params[:keyword])
        .or(Tour.by_city(params[:keyword]))
        .or(Tour.by_destination(params[:keyword]))
        .by_status(params[:status])
  end
end

app/controllers/api/v1/tours_controller.rb
class Api::V1::ToursController < Api::V1::ApplicationController
  before_action :authorized, except: %i(index show)
  before_action :set_tour, only: %i(show update destroy)

  # GET /api/v1/tours
  def index
    @tours = Tour.by_name(params[:name])
                 .by_status(params[:statuses])
                 .by_city(params[:city])

    render json: @tours, each_serializer: TourSerializer, status: :ok
  end

  # GET /api/v1/tours/:id
  def show
    render json: @tour, serializer: TourSerializer, status: :ok
  end

  # POST /api/v1/tours
  def create
    @tour = Tour.new(tour_params)

    if @tour.save
      render json: @tour, serializer: TourSerializer, status: :created
    else
      render json: ErrorSerializer.serialize(@tour.errors),
             status: :unprocessable_entity
    end
  end

  # PUT /api/v1/tours/:id
  def update
    if @tour.update(tour_params)
      render json: @tour, serializer: TourSerializer, status: :ok
    else
      render json: ErrorSerializer.serialize(@tour.errors),
             status: :unprocessable_entity
    end
  end

  # DELETE /api/v1/tours/:id
  def destroy
    if @tour.destroy
      render json: {
        status: true,
        message: I18n.t("api.tours.delete")
      }, status: :ok
    else
      render json: ErrorSerializer.serialize(@tour.errors),
             status: :unprocessable_entity
    end
  end

  private

  def set_tour
    @tour = Tour.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    render json: {
      status: false,
      message: I18n.t("api.tours.not_found")
    }, status: :not_found
  end

  def tour_params
    params.require(:tour).permit Tour::TOUR_ATTRIBUTES
  end
end

app/controllers/tours_controller.rb
class ToursController < ApplicationController
  before_action :tour, only: :show
  load_and_authorize_resource

  def show
    @relevant_pagy,
    @relevant_tours = pagy(Tour.by_tour_type_id(@tour.tour_type_id),
                           items: Settings.tour.rev_tours_per_page)

    @reviews = @tour.reviews.order_by_create_at
    return if params[:star].blank?

    @reviews = @reviews.by_rating(params[:star])
  end

  def index
    @q = Tour.ransack(params[:q])
    @tours = @q.result.by_status(params[:statuses])
    @pagy, @tours = pagy(@tours, items: Settings.tour.items_per_page)
  end

  private

  def tour
    @tour = Tour.find_by(id: params[:id])
    return if @tour.present?

    flash[:danger] = t "flash.tour.find_tour_failed"
    redirect_to tours_path
  end

  def search
    Tour::SEARCH_ATTRIBUTES.each do |field|
      @tours = @tours.public_send "by_#{field}", params[field]
    end
  end
end

app/helpers/admin/tours_helper.rb
module Admin::ToursHelper
  def filter_uploaded_images images
    images.select{|item| item.is_a?(ActionDispatch::Http::UploadedFile)}
  end

  def total_image_count_exceeds_limit? current_count, new_images, limit
    current_count + new_images.count > limit
  end

  def can_edit_tour tour
    tour.bookings.pending_or_past_confirmed.blank?
  end
end

app/views/tours/_carousel_inner.html.erb
<div class="carousel-item <%= "active" if index == 0 %>">
  <%= image_tag(image, alt: SecureRandom.uuid) %>
</div>   

app/views/tours/_relevant_tour.html.erb
<div class="col-12 col-md-5 m-2 col-lg-2 rev">
  <%= link_to relevant_tour do %>
    <div class="rev-tour rounded-3 d-flex flex-column">
      <h5 class="rev-name">
        <%= relevant_tour.tour_name %>
      </h5>
      <div class="d-flex flex-column gap-2">
        <span class="rev-dur">
          <b><%= t "tours.details.duration" %></b>
          <%= pluralize relevant_tour.day_duration, t("tours.day", count: relevant_tour.day_duration) %>
        </span>
      </div>
    </div>
  <% end %>
</div>

app/views/tours/_relevant_tours.html.erb
<div class="row mt-2">
  <h4>
    <%= t "tours.details.relevant" %>
  </h4>
  <div class="row">
    <%= render partial: "relevant_tour", collection: @relevant_tours %>
  </div>
  <%== pagy_nav(@relevant_pagy) %>
</div>

app/views/tours/_search_form.html.erb
<div class="tours-search-form">
  <%= search_form_for @q do |f| %>
    <div class="row">
      <div class="col-6">
        <%= f.label :tour_name_cont, t("tours.search.name") %>
        <%= f.search_field :tour_name_cont, class: "tours-search-input" %>
      </div>
      <div class="col-6">
        <%= f.label :address_cont, t("tours.search.city") %>
        <%= f.search_field :address_cont, class: "tours-search-input" %>
      </div>
    </div>
    <div class="row">
      <% Tour.statuses.each do |key, value| %>
        <div class="form-check">
          <%= check_box_tag "statuses[]", value, params[:statuses].present? && params[:statuses].include?(value), class: "form-check-input" %>
          <%= label_tag "tours.status.#{value}", t("tours.statuses.#{key}"), class: "form-check-label" %>
        </div>
      <% end %>
    </div>
    <div class="row">
      <div class="col-6">
        <%= f.label :status_eq, t("tours.search.status") %>
        <%= f.select :status_eq, Tour.statuses.to_a.map, {:include_blank => true} %>
      </div>
    </div>
    <div class="row mt-2">
      <div class="col-6 mx-auto">
        <%= submit_tag t("tours.search.action"), class: "btn btn-submit" %>
      </div>
    </div>
  <% end %>
</div>

app/views/tours/_total_rating.html.erb
<div class="card-body my-3">
  <div class="container d-flex">
    <div class="rating d-flex align-items-center fs-4" style="color: #f39c12;">
      <span><%= tour.reviews.average_rating %>/ <%= Settings.digit_5 %></span>
      <span class="ms-2">
        <% eval(Settings.star_range).each do %>
        <i class="fa fa-star"></i>
        <% end %>
      </span>
    </div>
    <div class="mx-3">
      <%= link_to t("reviews.all", count: tour.reviews.total_ratings),
          tour_path, class: "px-3 btn btn-outline-secondary mx-2" %>
      <%= link_to t("reviews.stars", count: tour.reviews.total_ratings_by_star(Settings.digit_5), stars: Settings.digit_5),
          tour_path(star: Settings.digit_5), class: "px-3 btn btn-outline-secondary mx-2" %>

      <%= link_to t("reviews.stars", count: tour.reviews.total_ratings_by_star(Settings.digit_4), stars: Settings.digit_4),
          tour_path(star: Settings.digit_4), class: "px-3 btn btn-outline-secondary mx-2" %>

      <%= link_to t("reviews.stars", count: tour.reviews.total_ratings_by_star(Settings.digit_3), stars: Settings.digit_3),
          tour_path(star: Settings.digit_3), class: "px-3 btn btn-outline-secondary mx-2" %>

      <%= link_to t("reviews.stars", count: tour.reviews.total_ratings_by_star(Settings.digit_2), stars: Settings.digit_2),
          tour_path(star: Settings.digit_2), class: "px-3 btn btn-outline-warning mx-2" %>

      <%= link_to t("reviews.star", count: tour.reviews.total_ratings_by_star(Settings.digit_1), stars: Settings.digit_1),
          tour_path(star: Settings.digit_1), class: "px-3 btn btn-outline-danger mx-2" %>
    </div>
  </div>
</div>

app/views/tours/_tour.html.erb
<div class="col-12 col-lg-6 tours-item">
  <%= link_to tour do %>
    <div class="tours-item-container border border-1 border-gray mx-auto p-2 rounded-3">
      <div class="tours-item-first">
        <span class="tours-item-name">
          <%= tour.tour_name %>
          <span class="tours-item-address"><%= tour.city %></span>
        </span>
        
        <span class="tours-item-duration">
          <%= t "tours.duration" %>
          <span class="black-text">
            <%= pluralize tour.day_duration, t("tours.day", count: tour.day_duration) %>
          </span>
        </span>
        <span class="tours-item-start">
          <%= t "tours.tour_destination" %>
          <span class="black-text">
            <%= tour.tour_destination %>
          </span>
        </span>
        <span class="tours-item-start">
          <%= t "tours.start" %>
          <span class="black-text">
            <%= tour.start_date %>
          </span>
        </span>
      </div>
      <div class="tours-item-second">
        <span class="tours-item-price">
          <%= t "tours.price" %>
          <%= tour.price %>
        </span>
      </div>
    </div>
  <% end %>
</div>

app/views/tours/index.html.erb
<div class="tours">
  <div class="row text-center pt-4 d-flex flex-column align-items-center">
    <h1 class="tours-title"><%= t "tours.title" %></h1>
    <p class="tours-subtitle"><%= t "tours.subtitle" %></p>
    <button class="tours-btn btn">
      <%= t "tours.show_search_form" %>
    </button>
  </div>
  <div class="tours-page">
    <div class="row pt-4 pb-4 tours-search">
      <%= render "search_form" %>
    </div>
    <div class="tours-container">
      <div class="row tours-container-inner">
        <%= render @tours %>
      </div>
      <div class="container py-5">
        <%== pagy_nav(@pagy) %>
      </div>
    </div>
  </div>
</div>

app/views/tours/show.html.erb
<div class="row my-4 tour mx-5">
  <div class="mb-6">
    <%= link_to t("tours.details.back"), tours_path %>
  </div>
  <div class="col-8 col-lg-12 d-flex flex-column gap-4">
    <h1>
      <%= @tour.tour_name %>
    </h1>
    <span>
      <b><%= t "tours.details.address" %></b>
      <%= @tour.city %>
      (<%= @tour.tour_destination %>)
    </span>
    <span>
      <b><%= t "tours.details.description" %></b>
      <%= @tour.description %>
    </span>
    <span>
      <b><%= t "tours.details.price" %></b>
      <%= @tour.price %>
    </span>
    <span>
      <b><%= t "tours.details.deposit_percent" %></b>
      <%= t "tours.details.deposit_percent_value", value: @tour.deposit_percent %>
    </span>
    <span>
      <b><%= t "tours.details.min_guests" %></b>
      <%= @tour.min_guests %>
      <b><%= t "tours.details.max_guests" %></b>
      <%= pluralize @tour.max_guests, t("tours.guest", count: @tour.max_guests) %>
    </span>
    <span>
      <b><%= t "tours.details.duration" %></b>
      <%= pluralize @tour.day_duration, t("tours.day", count: @tour.day_duration) %>
    </span>
    <span>
      <b><%= t "tours.details.from" %></b>
      <%= @tour.start_date %>
      <b><%= t "tours.details.to" %></b>
      <%= @tour.end_date %>
    </span>
    <div class="d-flex justify-content-start">
      <span class="tour-tag rounded-2">
        <%= t "tours.details.tag" %>
        <%= @tour.tour_type.type_name %>
      </span>
    </div>
    <% if @tour.active? %>
      <%= link_to t("book_tour_icon"), new_tour_booking_path(@tour), class: "btn btn-primary" %>
    <% else %>
      <div class="p-2 tour-status">
        <%= t "tours.details.status_noti" %>
        <%= t "tours.status.#{@tour.status}" %>
      </div>
    <% end %>
  </div>
  <div class="col-4 col-lg-12 image-box">
    <% if @tour.images.present? %>
      <div id="myCarousel" class="carousel slide">
        <div class="carousel-inner">
          <% @tour.images.each.with_index do |image, i| %>
            <%= render partial: "carousel_inner", locals: {image: image, index: i} %>
          <% end %>
        </div>
        <div class="carousel-control">
          <button class="left carousel-btn" data-slide="prev">
            <span class="sr-only">
              <%= t "tours.carousel_prev" %>
            </span>
          </button>
          <button class="right carousel-btn" data-slide="next">
            <span class="sr-only">
              <%= t "tours.carousel_next" %>
            </span>
          </button>
        </div>
      </div>
    <% else %>
      <span class="mx-auto"><%= t "tours.no_images" %></span>
    <% end %>
  </div>
  <hr class="my-5">
  <%= render "relevant_tours" %>
</div>

<div class="container my-5">
  <h5><%= t "review" %></h5>
  <div class="card col-10 my-4" style="background-color: #fffbf8">
    <%= render "total_rating" , tour: @tour %>
  </div>
  <% if user_signed_in? %>
    <%= render "reviews/form", review: @tour.reviews.build, tour: @tour %>
  <% end %>
</div>

<div id="reviews" class="my-3">
  <%= render partial: "reviews/review", collection: @reviews %>
</div>