config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users, controllers:
    {registrations: "users/registrations",
      confirmations: "users/confirmations",
      sessions: "users/sessions",
      passwords: "users/passwords",
      unlocks: "users/unlocks",
      omniauth_callbacks: "users/omniauth_callbacks"}

  resources :users, only: %i(new create show) do
    resources :bookings do
      member do
        patch :cancel
      end
    end
  end
  resources :account_activations, only: :edit

  namespace :admin do
    get "/", to: "admin#index"
    resources :tours do
      member do
        #remove_image_admin_tour_path
        delete :remove_image
      end
    end
    resources :vouchers
    resources :bookings, only: %i(index show destroy update)
  end

  resources :tours, only: %i(index show) do
    resources :bookings
    resources :reviews
  end
  root "static_pages#home"

  namespace :api do
    namespace :v1 do
      resources :tours
      resources :users
      post "users/sign_in", to: "users#sign_in"
      resources :reviews
    end
  end
end

app/views/admin/shared/_breadcrumb.html.erb
<nav aria-label="breadcrumb" class="mt-3">
  <ol class="breadcrumb">
    <% breadcrumbs.each do |crumb| %>
      <li class="breadcrumb-item">
        <% if crumb == breadcrumbs.last %>
          <span class="text-secondary"><%= crumb.name %></span>
        <% elsif crumb.link? %>
          <%= link_to crumb.name, crumb.path, class: "breadcrumb-link" %>
        <% else %>
          <span class="breadcrumb-page">
            <%= crumb.name %>
          </span>
        <% end %>
      </li>
    <% end %>
  </ol>
</nav>

app/views/admin/shared/_filght_ticket.html.erb
<table class="table table-striped table-hover my-4">
  <thead>
    <tr>
      <th><%= t "ticket_class" %></th>
      <th><%= t "number"  %></th>
      <th><%= t "airline_brand" %></th>
      <th><%= t "departure_time" %></th>
      <th><%= t "arrival_time" %></th>
      <th><%= t "origin" %></th>
      <th><%= t "destination" %></th>
    </tr>
  </thead>
  <tbody>
      <tr>
        <td><%= booking.flight_ticket.ticket_class %></td>
        <td><%= booking.number_of_guests %></td>
        <td><%= booking.flight.airline_brand %></td>
        <td><%= booking.flight.departure_time %></td>
        <td><%= booking.flight.arrival_time %></td>
        <td><%= booking.flight.origin_place %></td>
        <td><%= booking.flight.destination %></td>
      </tr>
  </tbody>
</table>

app/views/admin/shared/_navbar.html.erb
<header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow py-1">
  <%= link_to "Sun Asterisk" , admin_path, class:"navbar-brand col-md-3 col-lg-2 me-0 px-3" %>
    <input class="form-control mx-5" type="text" placeholder=<%=t "search" %> aria-label="Search">
    <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse"
      data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="navbar-nav f-flex">
      <div class="nav-item text-nowrap">
        <% if current_user.present? %>
          <%= button_to t("logout"), destroy_user_session_path, method: :delete, class:"nav-link px-3" %>
        <% end%>
      </div>
    </div>
</header>

app/views/admin/shared/_page_header.html.erb
<%= render "admin/shared/breadcrumb" %>
<div class="btn-toolbar mb-2 mb-md-0">
  <div class="btn-group me-2">
    <button type="button" class="btn btn-sm btn-outline-secondary"><%= t "share" %></button>
    <button type="button" class="btn btn-sm btn-outline-secondary"><%= t "export" %></button>
  </div>
  <button type="button" class="btn btn-sm btn-outline-secondary dropdown-toggle">
    <span data-feather="calendar"></span>
    <%= t "this_week" %>
  </button>
</div>

app/views/admin/shared/_vertical_navbar.html.erb
<nav id="sidebarAminMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
  <div class="position-sticky pt-3">
    <ul class="nav flex-column px-3">
      <%= link_to t("dashboard"), admin_path, class: "nav-link text-primary" %>
      <%= link_to t("tour_orders"), admin_bookings_path, class: "nav-link text-primary" %>
      <%= link_to t("tours_name"), admin_tours_path, class: "nav-link text-primary" %>
      <%= link_to t("customers"), admin_path, class: "nav-link text-primary" %>
      <%= link_to t("report"), admin_path, class: "nav-link text-primary" %>
    </ul>

    <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
      <span><%= t "saved_reports" %></span>
      <a class="link-primary" href="#" aria-label="Add a new report">
        <span data-feather="plus-circle"></span>
      </a>
    </h6>
    <ul class="nav flex-column mb-2 px-3">
      <%= link_to t("current_month"), admin_tours_path, class: "nav-link text-primary" %>
      <%= link_to t("last_quarter"), admin_path, class: "nav-link text-primary" %>
      <%= link_to t("voucher"), admin_vouchers_path, class: "nav-link text-primary" %>
    </ul>
  </div>
</nav>